### ISSUE TITLE
ToggleGroup & flag.Args()

### ISSUE THREAD

**Issue by tsaridas** [hedzr/cmdr#4]
Hi,
Maybe I'm missing what the feature ToggleGroup is but I thought that by setting a values like this would make the values mutually exclusive

```
                {
                        BaseOpt: cmdr.BaseOpt{
                                Short:       "L",
                                Full:        "list",
                                Description: "list command",
                                Group:       cStartup,
                        },
                        DefaultValue: false,
                        ToggleGroup:  "target",
                },
                {
                        BaseOpt: cmdr.BaseOpt{
                                Short:       "G",
                                Full:        "grain",
                                Description: "grain command",
                                Group:       cStartup,
                        },
                        DefaultValue: false,
                        ToggleGroup:  "target",
                },
```

but I can run both commands and I don't get an error.

Also, I would have wanted to have the option to get the remaining args that were not parsed just as in the official flag package.

**Comment by hedzr** [comment]
> but I can run both commands and I don't get an error.

If these two flags belong to the root command:
```golang
	rootCmd = &cmdr.RootCommand{
		Command: cmdr.Command{
			BaseOpt: cmdr.BaseOpt{
				Name:            appName,
				Description:     desc,
				LongDescription: longDesc,
				Examples:        examples,
			},

			// flags...

			Action: func(cmd *cmdr.Command, remainArgs []string) (err error) {
				// test if "--list" present
				if cmdr.GetBoolR("list") {
					// ...
				}
				// and test if "--grain" present
				if cmdr.GetBoolR("grain") {
					// ...
				}

				// or, use this new feature since v1.6.36 to test which one input
				if cmdr.GetStringR("target") == "list" {
					// ...
				}

				// as you seen, the parameter 'remainArgs' is what you want.

				return
			},
		},
	},
```

In our 'flag' sub-package, NArg() remains a problem, perhaps. In using `cmdr`, `Action(...)` is the __exact__ point to handler any hit command.

About the usage of `ToggleGroup`, its state has been flipped into the _option store_ in cmdr, so you can extract it by the codes above.

While using sub-commands, you have to extract the value with a dotted-path key with `<command>.<command>...<flag>` form, i.e., `cmdr.GetString("subcmd1.subcmd2.target")` will return the flipped state.

**Comment by hedzr** [comment]
I'm preparing more small, separate examples for this library, hope that they could be finalized soon and make the details clear.

**Comment by hedzr** [comment]
A standalone project published at:
https://github.com/hedzr/cmdr-examples
